place = ['greece','japan','canada','moroco','new zealand']
print('Here is the original list: ')
print(place)
print('Here is the sorted list: ')
print(sorted(place))
print('here is the original lists: ')
print(place)
print('reverse order list: ')
place.reverse()
print(place)
place.reverse()
print(place)
place.sort()
print('The list Order change Permanently')
print(place)